# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MAIND SUPSI dev
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

exclude: ['node_modules', 'Makefile', 'bourbon', 'neat']

collections:
  projects:
    name: Projects
    output: true
  news:
    name: News
    output: true
  students:
    name: Students
    output: true
  workshops:
    name: Workshops
    output: true
  openlectures:
    name: Openlectures
    output: true

defaults:
  -
    scope:
      type: projects
    values:
      layout: post
  -
    scope:
      type: students
    values:
      layout: post
  -
    scope:
      type: news
    values:
      layout: post
  -
    scope:
      type: workshops
    values:
      layout: post
  -
    scope:
      type: openlectures
    values:
      layout: post
